"""posts table

Revision ID: ef6d2de8820f
Revises: 68bbf73c4eb3
Create Date: 2020-08-29 16:48:43.258198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef6d2de8820f'
down_revision = '68bbf73c4eb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('summary', sa.String(length=40), nullable=True))
    op.add_column('post', sa.Column('title', sa.String(length=30), nullable=True))
    op.add_column('post', sa.Column('topic', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'topic')
    op.drop_column('post', 'title')
    op.drop_column('post', 'summary')
    # ### end Alembic commands ###
